// Code generated by hertz generator.

package main

import (
	handler "course/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.GET("/class_info", handler.GetClassInfo)
	// your code ...
}
