// Code generated by hertz generator.

package handler

import (
	"context"
	"course/biz/mysql"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, utils.H{
		"message": "pong",
	})
}

func GetClassInfo(ctx context.Context, c *app.RequestContext) {
	res, err := mysql.GetClassInfo(ctx)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{
			"error": err.Error(),
		})
	}
	c.JSON(consts.StatusOK, utils.H{
		"data": res,
	})
}